### ISSUE TITLE
Compilation failed with error: Abnormal build process termination:

### ISSUE THREAD

**Issue by peiyuwang** [pantsbuild/intellij-pants-plugin#133]
In working on #130 , after https://rbcommons.com/s/twitter/r/3819/ ignoring 'leaking' thread in tests, 

Last remaining failure is
```
There was 1 failure:
                     1) testHello(com.twitter.intellij.pants.integration.OSSPantsExamplesMultiTargetsIntegrationTest)
                     junit.framework.AssertionFailedError: Compilation failed with error: Abnormal build process termination: 
                     /usr/lib/jvm/java-8-oracle/jre/bin/java -Xmx700m -Djava.awt.headless=true -Djava.endorsed.dirs=\"\" -Dtest.mode=true -Djdt.compiler.useSingleThread=true -Dcompile.parallel=false -Drebuild.on.dependency.change=true -Djava.net.preferIPv4Stack=true -Dio.netty.initialSeedUniquifier=2113011163480761969 -Dfile.encoding=UTF-8 -Djps.file.types.component.name=CommunityFileTypes -Duser.language=en -Duser.country=US -Didea.home.path=/home/travis/build/peiyuwang/intellij-pants-plugin/.pants.d/intellij/plugins-sandbox/test -Didea.config.path=/home/travis/build/peiyuwang/intellij-pants-plugin/.pants.d/intellij/plugins-sandbox/test/config -Didea.plugins.path=/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins -Djps.log.dir=/home/travis/build/peiyuwang/intellij-pants-plugin/.pants.d/intellij/plugins-sandbox/test/system/log/build-log -Djava.io.tmpdir=/home/travis/build/peiyuwang/intellij-pants-plugin/.pants.d/intellij/plugins-sandbox/test/system/compile-server/_temp_ -classpath /home/travis/.ivy2/pants/com.intellij.sdk.community/jps-launcher.jar/jars/jps-launcher.jar-latest.jar:/home/travis/.ivy2/pants/jdk/tools.jar/jars/tools.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/optimizedFileManager.jar/jars/optimizedFileManager.jar-latest.jar org.jetbrains.jps.cmdline.Launcher /home/travis/.ivy2/pants/com.intellij.sdk.community/jdom.jar/jars/jdom.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/jna-platform.jar/jars/jna-platform.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/jsr166e.jar/jars/jsr166e.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/idea_rt.jar/jars/idea_rt.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/util.jar/jars/util.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/trove4j.jar/jars/trove4j.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/asm-all.jar/jars/asm-all.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/resources_en.jar/jars/resources_en.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/protobuf-2.5.0.jar/jars/protobuf-2.5.0.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/openapi.jar/jars/openapi.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/nanoxml-2.2.3.jar/jars/nanoxml-2.2.3.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/picocontainer.jar/jars/picocontainer.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/annotations.jar/jars/annotations.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/oromatcher.jar/jars/oromatcher.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/jps-model.jar/jars/jps-model.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/jgoodies-forms.jar/jars/jgoodies-forms.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/jps-builders.jar/jars/jps-builders.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/snappy-in-java-0.3.1.jar/jars/snappy-in-java-0.3.1.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/log4j.jar/jars/log4j.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/netty-all-4.1.0.Beta8.jar/jars/netty-all-4.1.0.Beta8.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/jps-builders.jar/jars/rt/jps-plugin-system.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/javac2.jar/jars/javac2.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/forms_rt.jar/jars/forms_rt.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/jna.jar/jars/jna.jar-latest.jar:/home/travis/.ivy2/pants/com.intellij.sdk.community/external-system-rt.jar/jars/external-system-rt.jar-latest.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.pants.d/compile/zinc/d4600a981d5d/jps-plugin.jps-plugin/396fbb2f3d50/z.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.pants.d/compile/zinc/d4600a981d5d/common.common/95a10ba3be08/z.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/jps-plugin:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/idea-dist/lib/rt/jps-plugin-system.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/jps-plugin/lib/gson-2.3.1.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins/Scala/lib/scala-library.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins/Scala/lib/compiler-settings.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins/Scala/lib/jps/nailgun.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins/Scala/lib/jps/scala-jps-plugin.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins/Scala/lib/jps/sbt-interface.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins/Scala/lib/jps/incremental-compiler.jar:/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/intellij/IC-145.597/plugins/Scala/lib/jps/jline.jar org.jetbrains.jps.cmdline.BuildMain 127.0.0.1 33013 b389891c-deef-4676-a001-dd655b5538d4 /home/travis/build/peiyuwang/intellij-pants-plugin/.pants.d/intellij/plugins-sandbox/test/system/compile-server
                     
                     	at junit.framework.Assert.fail(Assert.java:57)
                     	at junit.framework.TestCase.fail(TestCase.java:227)
                     	at com.twitter.intellij.pants.testFramework.PantsIntegrationTestCase.assertCompilerMessages(PantsIntegrationTestCase.java:342)
                     	at com.twitter.intellij.pants.testFramework.PantsIntegrationTestCase.makeProject(PantsIntegrationTestCase.java:324)
                     	at com.twitter.intellij.pants.integration.OSSPantsExamplesMultiTargetsIntegrationTest.testHello(OSSPantsExamplesMultiTargetsIntegrationTest.java:41)
                     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                     	at java.lang.reflect.Method.invoke(Method.java:483)
                     	at junit.framework.TestCase.runTest(TestCase.java:176)
                     	at com.intellij.testFramework.UsefulTestCase.access$001(UsefulTestCase.java:81)
                     	at com.intellij.testFramework.UsefulTestCase$2.run(UsefulTestCase.java:327)
                     	at com.intellij.openapi.externalSystem.test.ExternalSystemTestCase.invokeTestRunnable(ExternalSystemTestCase.java:268)
                     	at com.intellij.testFramework.UsefulTestCase.runTest(UsefulTestCase.java:343)
                     	at com.intellij.openapi.externalSystem.test.ExternalSystemTestCase.access$201(ExternalSystemTestCase.java:76)
                     	at com.intellij.openapi.externalSystem.test.ExternalSystemTestCase.runTest(ExternalSystemTestCase.java:250)
                     	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:370)
                     	at com.intellij.testFramework.UsefulTestCase$3.run(UsefulTestCase.java:427)
                     	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:26)
                     	at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:24)
                     	at com.intellij.testFramework.EdtTestUtilKt$sam$Runnable$ca4818df.run(EdtTestUtil.kt)
                     	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
                     	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
                     	at java.awt.EventQueue.access$500(EventQueue.java:97)
                     	at java.awt.EventQueue$3.run(EventQueue.java:702)
                     	at java.awt.EventQueue$3.run(EventQueue.java:696)
                     	at java.security.AccessController.doPrivileged(Native Method)
                     	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
                     	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
                     	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
                     	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
                     	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
                     	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                     	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                     	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                     	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                     	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                     	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
                     
                     FAILURES!!!
                     Tests run: 1,  Failures: 1
                     
                     com.twitter.intellij.pants.components.impl.PantsProjectCacheTest
                     	com.twitter.intellij.pants.components.impl.PantsProjectCacheTest#testEmpty
                     	com.twitter.intellij.pants.components.impl.PantsProjectCacheTest#testLastOne
                     	com.twitter.intellij.pants.components.impl.PantsProjectCacheTest#testFirstOne
                     
                     Time: 0.216
                     
                     OK (3 tests)
                     
                     com.twitter.intellij.pants.quickfix.AddPantsTargetDependencyFixTest
                     	com.twitter.intellij.pants.quickfix.AddPantsTargetDependencyFixTest#testBasic
                     	com.twitter.intellij.pants.quickfix.AddPantsTargetDependencyFixTest#testEmpty
                     	com.twitter.intellij.pants.quickfix.AddPantsTargetDependencyFixTest#testLast
                     
                     Time: 0.463
                     
                     OK (3 tests)
```                     

To repro, set environment variable `ADDITIONAL_ARGS` to `--test-junit-per-test-timer`.

**Comment by peiyuwang** [comment]
[133-log.txt](https://github.com/pantsbuild/intellij-pants-plugin/files/250016/133-log.txt)

Attaching raw log for posterity

**Comment by wisechengyi** [comment]
is this reproducible?

**Comment by peiyuwang** [comment]
fairly reproducible on ci, i would say 100% so far out of 3+ tries I did

**Comment by peiyuwang** [comment]
https://rbcommons.com/s/twitter/r/3831/ up for review, it's ng process taking space.

**Comment by peiyuwang** [comment]
ps: https://travis-ci.org/peiyuwang/intellij-pants-plugin/jobs/128186069 
```
                     pants: .DEBUG] Performing a fetch using ivy.
                     pants: 00:50:10 00:12       [bootstrap-scalastyle_2_10]
                     pants: DEBUG] Executing: /usr/lib/jvm/java-8-oracle/bin/java -Xmx1g -XX:MaxPermSize=256m -Dsun.io.useCanonCaches=false -Divy.cache.dir=/home/travis/.ivy2/pants -cp ../../../../../.ivy2/pants/org.apache.ivy/ivy/jars/ivy-2.4.0.jar:../../../../../.ivy2/pants/commons-httpclient/commons-httpclient/jars/commons-httpclient-3.1.jar:../../../../../.ivy2/pants/commons-logging/commons-logging/jars/commons-logging-1.0.4.jar:../../../../../.ivy2/pants/commons-codec/commons-codec/jars/commons-codec-1.2.jar:../../../../../.ivy2/pants/org.bouncycastle/bcpg-jdk14/jars/bcpg-jdk14-1.45.jar:../../../../../.ivy2/pants/org.bouncycastle/bcprov-jdk14/jars/bcprov-jdk14-1.45.jar org.apache.ivy.Main -settings /home/travis/build/peiyuwang/intellij-pants-plugin/.cache/pants/build-support/ivy/ivysettings.xml -ivy /home/travis/build/peiyuwang/intellij-pants-plugin/.cache/pants/.pants.d/ivy/bd71451c8628522b7f9f5455598d064e963537fd-IvyResolveFingerprintStrategy_53c4bb9c6553/fetch-ivy.xml -confs default -cachepath /home/travis/build/peiyuwang/intellij-pants-plugin/.cache/pants/.pants.d/ivy/bd71451c8628522b7f9f5455598d064e963537fd-IvyResolveFingerprintStrategy_53c4bb9c6553/classpath.raw.tmp.1593e5dfa9654712aee0e379c11fb1e8 args={'stderr': <pants.util.rwbuf.FileBackedRWBuf object at 0x48e6750>, 'stdout': <pants.util.rwbuf.FileBackedRWBuf object at 0x48e63d0>} at cwd=/home/travis/build/peiyuwang/intellij-pants-plugin/.cache/pants
```
Is what the last line is before the process crashed. This along with smaller targets pass while larger targets fail (less pants command vs more pants command generated by integration tests) leads to ng being the prime suspect.

**Comment by peiyuwang** [comment]
Reviewed at https://rbcommons.com/s/twitter/r/3831/ 
Submitted as 9a1ef40

Not 100% sure this is the root cause as there is no clear error message, but submitted since it makes a difference, we can revisit if this happens again.
