### ISSUE TITLE
Add ability to plugin to import another module to project to existing module using the 'Import Module.

### ISSUE THREAD

**Issue by tejal29** [pantsbuild/intellij-pants-plugin#19]
Currently this is not working. 

As mentioned by @ericzundel  in https://github.com/pantsbuild/intellij-pants-plugin/issues/5. 

====
I just imported the latest plugin built from HEAD and this is not a problem when I import a plain project.

commit ba6fb87528825821698e9402175a846fc6f23683
Author: fkorotkov <fkorotkov@twitter.com>
Date:   Wed Sep 24 09:20:31 2014 -0700
However, if I use the 'Import Module...' option and try to add a new module to my existing project I get a problem:

screen shot 2014-09-24 at 10 46 26 am

Here are the contents of idea.log

2014-09-24 10:46:13,184: Checking to see if pants.pex version has changed ...
2014-09-24 10:46:13,199: Checking to see if generated BUILD.* files are outdated in /Users/zundel/Development/java ...
2014-09-24 10:46:14,710: Finish checking BUILD.* health in 1.526 seconds.
(using pantsrc expansion: pants goal depmap --depmap-project-info --depmap-project-info-formatted --depmap-output-file=/private/var/folders/42/8krm7t_50x98_6rxp7p0tv1w000205/T/pants_run6525711466990458330.out --exclude-target-regexp=:aux-)

com.intellij.openapi.externalSystem.model.ExternalSystemException: Failed to update the project!

FAILURE: One or more target addresses are required.

FAILURE

2014-09-24 10:46:13,184: Checking to see if pants.pex version has changed ...
2014-09-24 10:46:13,199: Checking to see if generated BUILD.* files are outdated in /Users/zundel/Development/java ...
2014-09-24 10:46:14,710: Finish checking BUILD.* health in 1.526 seconds.
(using pantsrc expansion: pants goal depmap --depmap-project-info --depmap-project-info-formatted --depmap-output-file=/private/var/folders/42/8krm7t_50x98_6rxp7p0tv1w000205/T/pants_run6525711466990458330.out --exclude-target-regexp=:aux-)

    at com.twitter.intellij.pants.service.project.PantsResolver.resolve(PantsResolver.java:336)
    at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveUsingNewAPI(PantsProjectResolver.java:52)
    at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveProjectInfo(PantsProjectResolver.java:36)
    at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveProjectInfo(PantsProjectResolver.java:21)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
    at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
    at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
    at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
    at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:48)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:137)
    at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:123)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.execute(ExternalSystemUtil.java:406)
    at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3$1.run(ExternalSystemUtil.java:474)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$6.run(ProgressManagerImpl.java:281)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
    at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
    at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:645)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
====

**Comment by ericzundel** [comment]
@fkorotkov, is the next release of the plugin going to support importing multiple directories or adding another module?  This is the most requested feature from developers at Square.
