### ISSUE TITLE
Error importing project on Windows

### ISSUE THREAD

**Issue by joelthompson** [pantsbuild/intellij-pants-plugin#266]
When trying to import a project on a Windows machine, IntelliJ pops up a `Resolve Error` and this shows up in the IDE logs:

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at com.twitter.intellij.pants.service.PantsCompileOptionsExecutor.getProjectName(PantsCompileOptionsExecutor.java:115)
```

Line 115 is:
```java
String candidateName = String.join("__", buildRootPrefixedSpecs).replaceAll(File.separator, ".");
```
and on Windows, File.separator is `\`. The first argument to String.replaceAll is a regex, and `\` appears to be causing an error with the java regex parser. Ideally, File.separator should be regex-escaped before being passed into String.replaceAll.

**Comment by wisechengyi** [comment]
You are right. Generally speaking I do not have access to windows box, and testing it may be difficult. I can try to fix it, but PR would be more welcome.

Although I am sort of surprised that Pants works on windows, @joelthompson have you verified that it works for your use case at least?

**Comment by svefors** [comment]
He might be using windows sub system for linux?
