### ISSUE TITLE
mysql_config errors in importing a pants project

### ISSUE THREAD

**Issue by apurva-sharma** [pantsbuild/intellij-pants-plugin#293]
Hello,

I am able to build all artifacts of a pants project from the command line.
However, when I try to import the project in intellij 2017.1.1 with pants plugin (1.6.0) on macOsX, I run into the following issues 

```
Error:pants export --formatted ./:: --export-output-file=/private/var/folders/8s/drywdwvx26sc7s9knqtf7l7n35q3vj/T/pants_depmap_run547.out
Exit code: 1
[31m
FAILURE[0m

**** Failed to install mysqlclient-1.3.7 (caused by: NonZeroExit("received exit code 1 during execution of `[u'/usr/bin/python', '-', 'bdist_wheel', '--dist-dir=/var/folders/8s/drywdwvx26sc7s9knqtf7l7n35q3vj/T/tmpwzN071']` while trying to execute `[u'/usr/bin/python', '-', 'bdist_wheel', '--dist-dir=/var/folders/8s/drywdwvx26sc7s9knqtf7l7n35q3vj/T/tmpwzN071']`",)
):
stdout:

stderr:
sh: mysql_config: command not found
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "setup.py", line 17, in <module>
    metadata, options = get_config()
  File "setup_posix.py", line 44, in get_config
    libs = mysql_config("libs_r")
  File "setup_posix.py", line 26, in mysql_config
    raise EnvironmentError("%s not found" % (mysql_config.path,))
EnvironmentError: mysql_config not found


Exception caught: (<class 'pex.resolver.Untranslateable'>)

Exception message: Package SourcePackage(u'file:///Users/apsharma/xxx/data-processing/.pants.d/python-setup/resolved_requirements/CPython-2.7.10/mysqlclient-1.3.7.tar.gz') is not translateable by ChainedTranslator(WheelTranslator, EggTranslator, SourceTranslator)
```
I do have the correct version of mysqlclient:
```
pip install 'mysqlclient===1.3.7' --force
```

mql_config seems to be available in bash too:

```
─± mysql_config
Usage: /usr/local/bin/mysql_config [OPTIONS]
Compiler: Clang 8.0.0.8000042
Options:
        --cflags         [-I/usr/local/Cellar/mysql/5.7.18_1/include/mysql ]
        --cxxflags       [-I/usr/local/Cellar/mysql/5.7.18_1/include/mysql ]
        --include        [-I/usr/local/Cellar/mysql/5.7.18_1/include/mysql]
        --libs           [-L/usr/local/Cellar/mysql/5.7.18_1/lib -lmysqlclient -lssl -lcrypto]
        --libs_r         [-L/usr/local/Cellar/mysql/5.7.18_1/lib -lmysqlclient -lssl -lcrypto]
        --plugindir      [/usr/local/Cellar/mysql/5.7.18_1/lib/plugin]
        --socket         [/tmp/mysql.sock]
        --port           [0]
        --version        [5.7.18]
        --libmysqld-libs [-L/usr/local/Cellar/mysql/5.7.18_1/lib -lmysqld -lssl -lcrypto]
        --variable=VAR   VAR is one of:
                pkgincludedir [/usr/local/Cellar/mysql/5.7.18_1/include/mysql]
                pkglibdir     [/usr/local/Cellar/mysql/5.7.18_1/lib]
                plugindir     [/usr/local/Cellar/mysql/5.7.18_1/lib/plugin]
```
Any pointers on fixing this?

Thanks,
Apurva

**Comment by apurva-sharma** [comment]
Update: 
To be perfectly sure, I created a new virtual env, and set the project sdk to point to that python.
I continue to run into this issue,  any idea about this?

**Comment by wisechengyi** [comment]
Hi @apurva-sharma, sorry about the delay. This is more of a pants/pex issue.

How pex resolves dependencies is a different story. I've transfer the issue to https://github.com/pantsbuild/pants/issues/4621
