### ISSUE TITLE
Cannot import a Pants project - Resolve error

### ISSUE THREAD

**Issue by pvcnt** [pantsbuild/intellij-pants-plugin#35]
I'm using the Pants plugin version 1.1.1. When I try to import a Pants project by selecting the root directory (with a BUILD file inside) I got a "Resolve error – Failed to update the project!". Below is my Intellij error log.

```
2015-02-26 11:56:16,121 [97199434]   INFO - .service.project.PantsResolver - WARNING: Specifying 'goal' explicitly is no longer necessary, and deprecated.

Exit code 1 
2015-02-26 11:56:16,464 [97199777]   WARN - nal.AbstractExternalSystemTask - Failed to update the project! 
com.twitter.intellij.pants.PantsExecutionException: Failed to update the project!
	at com.twitter.intellij.pants.service.project.PantsResolver.resolve(PantsResolver.java:511)
	at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveUsingPantsGoal(PantsProjectResolver.java:116)
	at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveProjectInfo(PantsProjectResolver.java:70)
	at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveProjectInfo(PantsProjectResolver.java:34)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:137)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:123)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.execute(ExternalSystemUtil.java:477)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3$1.run(ExternalSystemUtil.java:545)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$7.run(ProgressManagerImpl.java:422)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:641)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by tejal29** [comment]
Is this still an  issue? Have you tried the latest pants version?

**Comment by pvcnt** [comment]
Yes, and I'm working with Pants 0.0.28.

**Comment by fkorotkov** [comment]
Could you please attache idea.log for details of the error. To get idea.log file: Help -> Show Log in Finder.

**Comment by pvcnt** [comment]
Hi,

I don't really want to post my entire idea.log on GitHub. But what appears in the log during my try to import the Pants project is the following:

```
2015-03-25 13:01:53,611 [186127634]   INFO - .service.project.PantsResolver - WARNING: Specifying 'goal' explicitly is no longer necessary, and deprecated.

Exit code 1 
2015-03-25 13:01:53,612 [186127635]   WARN - nal.AbstractExternalSystemTask - Failed to update the project! 
com.twitter.intellij.pants.PantsExecutionException: Failed to update the project!
	at com.twitter.intellij.pants.service.project.PantsResolver.resolve(PantsResolver.java:513)
	at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveUsingPantsGoal(PantsProjectResolver.java:116)
	at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveProjectInfo(PantsProjectResolver.java:70)
	at com.twitter.intellij.pants.service.project.PantsProjectResolver.resolveProjectInfo(PantsProjectResolver.java:34)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:41)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl$1.produce(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:59)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:49)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:51)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:137)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:123)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.execute(ExternalSystemUtil.java:477)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3$1.run(ExternalSystemUtil.java:545)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:621)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$7.run(ProgressManagerImpl.java:422)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.application.impl.ApplicationImpl$10$1.run(ApplicationImpl.java:641)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by fkorotkov** [comment]
weird. it should contain cmd output as well. could you please try this command on a target you are trying to import:

./pants depmap --depmap-project-info path/to/target:name

the plugin calls it and it seems it failed

**Comment by pvcnt** [comment]
When I specify a specific goal it produces a well-formed JSON file. But after diving a little bit in the plugin code (from what I saw [there](https://github.com/pantsbuild/intellij-pants-plugin/blob/ee9151b5cdd366a85fc4cc79cc29fd145d9f629c/src/com/twitter/intellij/pants/service/project/PantsResolver.java#L542)), if I specify all goals (either ```./pants depmap .:``` or ```./pants depmap .::```) I got an error message: "FAILURE: Ivy returned 1".

**Comment by fkorotkov** [comment]
could it be this issues https://github.com/pantsbuild/jmake/issues/13 ?

BTW are you sure you don't see these ivy failures in idea.log? Also I recently submitted a patch to IntelliJ to provide a quick way to open a log file from this dialog. So UX should be improved soon.

**Comment by pvcnt** [comment]
Yes, it's strange I don't see any log. The only error logs I'm able to see are by using Pants' server. I think we can say it's a problem related either to Pants itself or my specific local setup and not to Intellij plugin. I'll try to investigate further. Thanks for you help!
