### ISSUE TITLE
Tests fails after opening project in IDEA

### ISSUE THREAD

**Issue by LantAlex** [pantsbuild/intellij-pants-plugin#41]
I got actual version of  this plugin. At first time command ./scripts/run-tests-ci.sh worked fine, but after opening plugin sources in IDEA, tests fails. There are 2 errors: 

1)
testMissingDepsWhiteList(com.twitter.intellij.pants.highlighting.PantsUnresolvedJavaReferenceQuickFixProviderTest)
java.lang.AssertionError: null
at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
at com.intellij.testFramework.TestLogger.error(TestLogger.java:67)

2) testMissingDepsWhiteList(com.twitter.intellij.pants.highlighting.PantsUnresolvedScalaReferenceQuickFixProviderTest)
java.lang.AssertionError: null
at com.intellij.testFramework.LoggedErrorProcessor.processError(LoggedErrorProcessor.java:56)
at com.intellij.testFramework.TestLogger.error(TestLogger.java:67)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)

I reset ("git reset --hard") sources, closed IDEA, reboot my OS, but that errors remains. How to resolve this issue? I can't test my changes for this plugin.

**Comment by tejal29** [comment]
hi @LantAlex do you still see this error?
