### ISSUE TITLE
File type detector com.twitter.intellij.pants.file.BUILDFileTypeDetector@292dba72 does not implement getDetectedFileTypes(), leading to suboptimal performance.

### ISSUE THREAD

**Issue by wisechengyi** [pantsbuild/intellij-pants-plugin#431]
```
com.intellij.diagnostic.PluginException: File type detector com.twitter.intellij.pants.file.BUILDFileTypeDetector@292dba72 does not implement getDetectedFileTypes(), leading to suboptimal performance. Please implement the method. [Plugin: com.intellij.plugins.pants]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:399)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:58)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getDetectorsForType(FileTypeManagerImpl.java:1128)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.isFileOfType(FileTypeManagerImpl.java:1182)
	at com.intellij.util.xml.impl.DomManagerImpl$3.visitFile(DomManagerImpl.java:155)
	at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:110)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:291)
	at com.intellij.util.xml.impl.DomManagerImpl.calcDomChangeEvents(DomManagerImpl.java:152)
	at com.intellij.util.xml.impl.DomManagerImpl.access$100(DomManagerImpl.java:64)
	at com.intellij.util.xml.impl.DomManagerImpl$2.prepareChange(DomManagerImpl.java:118)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.lambda$runAsyncListeners$0(AsyncEventSupport.java:76)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:825)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:62)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.runAsyncListeners(AsyncEventSupport.java:76)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.tryProcessingEvents(RefreshQueueImpl.java:147)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.lambda$processAndFireEvents$3(RefreshQueueImpl.java:132)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.processAndFireEvents(RefreshQueueImpl.java:132)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.lambda$scheduleAsynchronousPreprocessing$2(RefreshQueueImpl.java:105)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wisechengyi** [comment]
Looks like the issue still exists.
