### ISSUE TITLE
project lifecycle issue

### ISSUE THREAD

**Issue by wisechengyi** [pantsbuild/intellij-pants-plugin#444]
https://gist.github.com/wisechengyi/eab3389ed28934bd9e7c82e0a34ca82d

**Comment by wisechengyi** [comment]
1. Start running the child intellij. Then closing the child intellij would have:
```
java.lang.NullPointerException
	at com.twitter.intellij.pants.components.impl.PantsInitComponentImpl.disposeComponent(PantsInitComponentImpl.java:46)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:106)
	at com.intellij.openapi.application.impl.ApplicationImpl.dispose(ApplicationImpl.java:361)
	at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:104)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:183)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:133)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:116)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:112)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$disposeSelf$2(ApplicationImpl.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:180)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:655)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:628)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:617)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:613)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:584)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:579)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame$3.windowClosing(WelcomeFrame.java:108)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2078)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2037)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

https://www.youtube.com/watch?v=ASU-5mDv6Bo&feature=youtu.be

2. We currently have a hack in the `tearDown`, so it would be good to figure out where we are double disposing things then remove the hack.

https://github.com/pantsbuild/intellij-pants-plugin/blob/d6eabd670dc40fad9915daa9afacd4ec574e4eda/testFramework/com/twitter/intellij/pants/testFramework/PantsIntegrationTestCase.java#L535-L540

**Comment by marek1840** [comment]
```
java.lang.NullPointerException
	at com.twitter.intellij.pants.components.impl.PantsInitComponentImpl.disposeComponent(PantsInitComponentImpl.java:46)
```
happens because the `PantsMetrics` gets initialized only after some a gets opened. If we close IntelliJ without doing so, a nullpointer happens.

We could either initialize metrics in `PantsInitComponent` or add a guard against the null.

**Comment by tpasternak** [comment]
1. As Marek said, problem no. 1 can be fixed by just adding a guard against null there. It works and IMO it's quite clean.

2. Problem no. 2 isn't realted to no.1 It comes from the fact that at startup, the `prepareIDE` function asynchronously spawns an anonymous function that operates on `project` variable. Unfortunately, the variable is destroyed in `ExternalSystemTestCase` 's `tearDown`. Sometimes the `prepareIDE` function is scheduled for execution after the test's `tearDown` and that's why crash happens.
