### ISSUE TITLE
Write access is allowed from event dispatch thread only

### ISSUE THREAD

**Issue by pvcnt** [pantsbuild/intellij-pants-plugin#81]
When trying to update my Pants project, I systematically get the following error: "Write access is allowed from event dispatch thread only". It is annoying since it prevents me from getting new modules for new Pants packages.

I have the last version of everything (Pants, Intellij, Pants plugin). I tried reinstalling Intellij and the plugin from scratch, but I can't get a rid of that error.

Here are the details of the crash report:

```
Write access is allowed from event dispatch thread only
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@5c37da86 Current thread: Thread[ApplicationImpl pooled thread 13,4,main] 333115689 SystemEventQueueThread: Thread[AWT-EventQueue-0 15.0.2#IU-143.1184.17, eap:false,6,main] 856088930

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:497)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:1106)
	at com.intellij.openapi.application.impl.ApplicationImpl.d(ApplicationImpl.java:1212)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1012)
	at com.twitter.intellij.pants.service.python.PantsPythonSetupDataService.importData(PantsPythonSetupDataService.java:68)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.a(ProjectDataManager.java:254)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:151)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:206)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManager.importData(ProjectDataManager.java:212)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$MyMultiExternalProjectRefreshCallback.onSuccess(ExternalSystemUtil.java:858)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:447)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4$2.run(ExternalSystemUtil.java:500)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

Thanks.

**Comment by wisechengyi** [comment]
1. Are you on IntelliJ 15 and the latest plugin?
2. Which target was imported (hopefully from OSS pants so I can try to repro exactly)
3. What is the exact operation you are trying to do that will result in this error?

**Comment by wisechengyi** [comment]
can't repro

**Comment by pvcnt** [comment]
Sorry, I forgot to reply. Indeed, I don't have this error anymore with Intellij 16 and the latest version of the plugin.

**Comment by Manish6858** [comment]
So the problem was concluded in that android studio conflicted with my installed jdk version, so it was resolved when i checked jdk location (File -> Project Structure -> SDK Location)

**Comment by wisechengyi** [comment]
Great, thanks for the looping back!

**Comment by 001lilou** [comment]
It's works. thank's

**Comment by LeonidIvankin** [comment]
https://stackoverflow.com/questions/56311758/upgraded-androidstudio-to-3-4-1-and-gradle-problems
